server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always #색깔

    url: jdbc:h2:./db_dev;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:

        format_sql: true
        default_batch_fetch_size: 100
        highlight-sql: true


        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true  # SQL 쿼리 로그를 출력
  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 콘솔 경로 (기본값: /h2-console)
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "${custom.site.backUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:3000"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: book.oa.gg
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name: Book


aladin:
  ttbkey:

