server:
  port: 8080
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: jjevt3Hsy0331@
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always #색깔
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        highlight-sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true  # SQL 쿼리 로그를 출력
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "${custom.site.backUrl}/{action}/oauth2/code/{registrationId}"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
custom:
  prod:
    cookieDomain: book.oa.gg
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
    name: Book

  jwt:
    secret: "w92mLzTnRJ6P1qfzX7KlmFdyvRk3NhGq"

  aladin:
    ttbkey: "ttbkumjjick2245001"