spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
<<<<<<< HEAD
    password: ${MYSQLPASSWORD}
=======
    password: jjevt3Hsy0331@
>>>>>>> origin/feature-order-search
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always #색깔

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
<<<<<<< HEAD
      ddl-auto: update
=======
      ddl-auto: update
    custom:
      jwt:
        secret: "w92mLzTnRJ6P1qfzX7KlmFdyvRk3NhGq"
>>>>>>> origin/feature-order-search
